name: Reusable workflow example

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Pass input and secrets to node
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/node.yml@master
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.token }}
