name: Reusable workflow example

on:
  workflow_dispatch:
  workflow_call:
    
jobs:
  example_job:
    name: call-workflow-passing-data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/node.yml@master
        
